### PR TITLE
docs:(quickstart): set Deploy a Test Application version to v1.0.3

### PR DESCRIPTION
**Pull request by lnsyyj**
Update kubectl deployment examples to Deploy a Test Application Mayastor v1.0.3

Signed-off-by: JiangYu <lnsyyj@hotmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
@lnsyyj I think this should be raised against the version/1.0 branch instead.
Develop is for the next version and deploy has actually been removed so we need to update that section and place the yaml file elsewhere @GlennBullingham

**Review by GlennBullingham — CHANGES_REQUESTED** [review]
As @tiagolobocastro has previously commented, this PR should be raised against the release/1.0 branch, not develop (which represents the "next" vesion, in this case the Mayastor 2.x family).

Also, the commit msg needs to conform to Conventional Commit format - there is an extraneous colon after "docs" and before the opening parenthesis.

**Comment by lnsyyj** [comment]
Hi @GlennBullingham ,

When I fork the mayastor-docs repository and clone my private mayastor-docs repository, I can't see the release/1.0 branch.
````
root@spdk-1:~/github/mayastor-docs# git remote -v
origin	git@github.com:lnsyyj/mayastor-docs.git (fetch)
origin	git@github.com:lnsyyj/mayastor-docs.git (push)

root@spdk-1:~/github/mayastor-docs# git branch -a
* develop
   remotes/origin/HEAD -> origin/develop
   remotes/origin/develop
   remotes/origin/local-develop
````

Document format I refer to this PR:
https://github.com/openebs/mayastor-docs/pull/68

**Comment by tiagolobocastro** [comment]
> origin	git@github.com:lnsyyj/mayastor-docs.git (fetch)

Seems your origin is your own fork so that's why it's not there.
If not already there you can try adding it. Something like this:
`git remote add openebs git@github.com:openebs/mayastor-docs.git`

**Comment by lnsyyj** [comment]
OK @tiagolobocastro , I opened a new PR. This PR can be closed.

new PR:
https://github.com/openebs/mayastor-docs/pull/84

**Pull request closed without merging**
