### PR TITLE
Cherry-pick #196 to version/2.3

### PR DESCRIPTION
**Pull request by vikgaur**
The change cherry-picks the commits from #196 to version/2.3

### CODE REVIEW

**Comment by avishnu** [comment]
There are conflicts in this PR. Check the changes please

**Comment by vikgaur** [comment]
@avishnu, made the changes. Please take a look.

**Comment by avishnu** [comment]
> @avishnu, made the changes. Please take a look.

the conflicts have been resolved, but there are absolute links (pointing to a wrong branch) instead of relative links. Also, the change in deploy-mayastor.md is not included.

**Comment by vikgaur** [comment]
@avishnu fixed the issue. Please review.

**Review by avishnu — APPROVED** [review]
Lgtm

**Pull request merged**
